client: Fix push command with aiohttp >= 3.10.6
In aiohttp 3.10.6 https://github.com/aio-libs/aiohttp/pull/6485 a new
abstract method was implemented in aiohttp.Payload. So trying to
instantiate the AsyncNamedFilePart class fails and causes the push
command to fail:

```
  File "/usr/sbin/flat-manager-client", line 350, in upload_objects
    named = get_object_multipart(repo_path, file_obj)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/sbin/flat-manager-client", line 738, in get_object_multipart
    return AsyncNamedFilePart(
           ^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class AsyncNamedFilePart without an
implementation for abstract method 'decode'
```

Create a placeholder method for now.